In [47]:
from tensorflow.keras.preprocessing.text import one_hot

In [48]:
### sentences
sent=[  'the glass of milk',
     'the glass of juice',
     'the cup of tea',
    'I am a good boy',
     'I am a good developer',
     'understand the meaning of words',
     'your videos are good',]

In [49]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [50]:
## Define the vocabulary size
voc_size=10000

In [51]:
sent

['the glass of milk',
 'the glass of juice',
 'the cup of tea',
 'I am a good boy',
 'I am a good developer',
 'understand the meaning of words',
 'your videos are good']

In [52]:
### One Hot Representation
one_hot_repr=[one_hot(words,voc_size)for words in sent]
one_hot_repr

[[843, 1764, 1510, 6986],
 [843, 1764, 1510, 4921],
 [843, 5677, 1510, 5272],
 [4313, 6730, 4129, 1705, 8669],
 [4313, 6730, 4129, 1705, 7423],
 [5379, 843, 4386, 1510, 2710],
 [3091, 3705, 8343, 1705]]

In [53]:
## word Embedding Representation

from tensorflow.keras.layers import Embedding
#from tensorflow.keras.processing.sequence import pad_sequences
from tensorflow.keras.utils import pad_sequences
from tensorflow.keras.models import Sequential

In [54]:
import numpy as np

In [55]:
sent_length=8
embedded_docs=pad_sequences(one_hot_repr,padding='pre',maxlen=sent_length)
print(embedded_docs)

[[   0    0    0    0  843 1764 1510 6986]
 [   0    0    0    0  843 1764 1510 4921]
 [   0    0    0    0  843 5677 1510 5272]
 [   0    0    0 4313 6730 4129 1705 8669]
 [   0    0    0 4313 6730 4129 1705 7423]
 [   0    0    0 5379  843 4386 1510 2710]
 [   0    0    0    0 3091 3705 8343 1705]]


In [56]:
## feature representation
dim=10

In [57]:
model=Sequential()
model.add(Embedding(voc_size,dim,input_length=sent_length))
model.compile('adam','mse')

In [58]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_3 (Embedding)     (None, 8, 10)             100000    
                                                                 
Total params: 100000 (390.62 KB)
Trainable params: 100000 (390.62 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [59]:
model.predict(embedded_docs)

1/1 [==============================] - 0s 28ms/step


array([[[-3.18802521e-03,  3.28684337e-02, -3.68535519e-04,
          2.87356041e-02, -9.93484259e-03,  3.71618606e-02,
          4.14257981e-02, -4.35914770e-02, -9.78172943e-03,
          2.09757946e-02],
        [-3.18802521e-03,  3.28684337e-02, -3.68535519e-04,
          2.87356041e-02, -9.93484259e-03,  3.71618606e-02,
          4.14257981e-02, -4.35914770e-02, -9.78172943e-03,
          2.09757946e-02],
        [-3.18802521e-03,  3.28684337e-02, -3.68535519e-04,
          2.87356041e-02, -9.93484259e-03,  3.71618606e-02,
          4.14257981e-02, -4.35914770e-02, -9.78172943e-03,
          2.09757946e-02],
        [-3.18802521e-03,  3.28684337e-02, -3.68535519e-04,
          2.87356041e-02, -9.93484259e-03,  3.71618606e-02,
          4.14257981e-02, -4.35914770e-02, -9.78172943e-03,
          2.09757946e-02],
        [ 4.67282571e-02,  3.46276201e-02,  1.14341155e-02,
          1.08131282e-02,  4.19282578e-02,  4.79418039e-03,
          2.34739073e-02, -3.72104868e-02, -3.597896

In [60]:
embedded_docs[0]

array([   0,    0,    0,    0,  843, 1764, 1510, 6986])

In [61]:
model.predict(embedded_docs[0])

1/1 [==============================] - 0s 26ms/step


array([[-0.00318803,  0.03286843, -0.00036854,  0.0287356 , -0.00993484,
         0.03716186,  0.0414258 , -0.04359148, -0.00978173,  0.02097579],
       [-0.00318803,  0.03286843, -0.00036854,  0.0287356 , -0.00993484,
         0.03716186,  0.0414258 , -0.04359148, -0.00978173,  0.02097579],
       [-0.00318803,  0.03286843, -0.00036854,  0.0287356 , -0.00993484,
         0.03716186,  0.0414258 , -0.04359148, -0.00978173,  0.02097579],
       [-0.00318803,  0.03286843, -0.00036854,  0.0287356 , -0.00993484,
         0.03716186,  0.0414258 , -0.04359148, -0.00978173,  0.02097579],
       [ 0.04672826,  0.03462762,  0.01143412,  0.01081313,  0.04192826,
         0.00479418,  0.02347391, -0.03721049, -0.03597896,  0.03537193],
       [ 0.02949871,  0.04895281, -0.01107734,  0.01948654, -0.02309157,
        -0.02469572,  0.00385167,  0.00645889, -0.00926535, -0.02973145],
       [ 0.02658044,  0.00040674, -0.01483386,  0.04443145,  0.03241492,
        -0.04594544,  0.00516136, -0.02570586